baseurl = "https://weirdtrickmafia.fm"
languageCode = "en-us"
title = "weirdtrickmafia.fm"
canonifyUrls = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
description = "A podcast about tech, feelings, open source, and /dev/urandom."
itunes_podcast_url = "https://itunes.apple.com/us/podcast/weirdtrickmafia-fm/id1456548333?mt=2"
google_play_podcast_url = "https://playmusic.app.goo.gl/?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&apn=com.google.android.music&link=https://play.google.com/music/m/Ithpij5edvyliymmbmg3d6ofyiy?t%3Dweirdtrickmafia.fm%26pcampaignid%3DMKT-na-all-co-pr-mu-pod-16"
stitcher_podcast_url = "https://www.stitcher.com/s?fid=383697&refid=stpr"
github_url = "https://github.com/jessfraz/weirdtrickmafia.fm"
twitter_handle = "weirdtrickmafia"
youtube_url = "https://www.youtube.com/channel/UC5mxyAYNjOR1dqXeyzxW_uw"
	[params.feed]
	feed_copyright = "Copyright 2019 weirdtrickmafia.fm" #do not use markdown in this field; it is used in the feed
	itunes_subtitle = "/dev/urandom" #no markdown or HTML
	itunes_author = "Jessie Frazelle and Andrew Clay Shafer" #no markdown or HTML
	itunes_summary = "A podcast about tech, feelings, open source, and /dev/urandom."
	itunes_owner_name = "Jessie Frazelle"
	itunes_owner_email = "jfrazelle@me.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
	itunes_image = "https://weirdtrickmafia.fm/img/podcast_logo.png" #fqdn to the image art for your podcast
	itunes_top_category = "Technology"
	itunes_first_sub_category = "Software How-To"
	itunes_second_sub_category = "Tech News"
